// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKnobS93MNZQu5vKXCjfWHBNzKz8tj8U',
    appId: '1:774658616987:web:9dc686ac6d4548a34a203e',
    messagingSenderId: '774658616987',
    projectId: 'attendance-collab',
    authDomain: 'attendance-collab.firebaseapp.com',
    storageBucket: 'attendance-collab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNLaGCp2UBOvFkV5-xlKW49pKmebtrIM4',
    appId: '1:774658616987:android:af8df46e3f24291e4a203e',
    messagingSenderId: '774658616987',
    projectId: 'attendance-collab',
    storageBucket: 'attendance-collab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfrT2hQIXHf7oZ4opAHoj8iDpJUj24Icw',
    appId: '1:774658616987:ios:f504d5abfc3d24544a203e',
    messagingSenderId: '774658616987',
    projectId: 'attendance-collab',
    storageBucket: 'attendance-collab.appspot.com',
    iosClientId: '774658616987-dqjl0igrc4484qhs52rvthokuk4csf7n.apps.googleusercontent.com',
    iosBundleId: 'com.rds.attendanceCollab',
  );
}
